export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const INIT_INGREDIENTS_ERROR = 'INIT_INGREDIENTS_ERROR';

export const ORDER_CLICK_INIT = 'ORDER_CLICK_INIT';
export const ORDER_CLICKED = 'ORDER_CLICKED';
export const ORDER_SUCCESS = 'ORDER_SUCESS';
export const ORDER_ERROR ='ORDER_ERROR';
export const CHECKOUT_INIT = 'CHECKOUT_INIT';

export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR';